name: yolo-world
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libcublas
  - libcufft
  - libcufile
  - libcurand
  - libcusolver
  - libcusparse
  - libffi
  - libgcc
  - libgcc-ng
  - libgomp
  - libnpp
  - libnsl
  - libnvjpeg
  - libstdcxx
  - libstdcxx-ng
  - libuuid
  - libxcb
  - libzlib
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - pytorch-cuda=11.8
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - addict==2.4.0
      - blinker==1.9.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.3.1
      - cmake==3.25.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.19.1
      - flask==3.1.2
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.4
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lit==15.0.7
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - mmdet==3.0.0
      - mmengine==0.10.7
      - mmyolo==0.6.0
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - opencv-python==4.8.1.78
      - packaging==25.0
      - pillow==10.2.0
      - platformdirs==4.5.0
      - prettytable==3.17.0
      - pycocotools==2.0.10
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.1
      - regex==2025.11.3
      - requests==2.31.0
      - rich==14.2.0
      - safetensors==0.7.0
      - scipy==1.11.4
      - shapely==2.1.2
      - six==1.17.0
      - sympy==1.14.0
      - termcolor==3.2.0
      - terminaltables==3.1.10
      - tokenizers==0.15.2
      - tomli==2.3.0
      - tqdm==4.66.1
      - transformers==4.36.2
      - triton==2.0.0
      - typing-extensions==4.15.0
      - urllib3==1.26.13
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - yapf==0.43.0
